title: James Kentling Campbell # your name (or website title) here
logo: "/images/0.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master of Science in Business Analytics Graduate Student (2021)
  <br><br>
  Data Analyst, Geophysicist, Non-Profit Treasurer
  <br><br>
  <a href="https://www.linkedin.com/in/jameskentlingcampbell/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
