title: James Kentling Campbell 
logo: "/images/0.jpeg?raw=true" 
description: > 
  Master of Science in Business Analytics <br>
  Master of Science in Geology <br>
  Bachelor of Arts in Geology <br>
  <br>
  Data Analyst <br>
  Geophysicist <br>
  Non-Profit Treasurer <BR>
  <br>
  <a href="https://www.linkedin.com/in/jameskentlingcampbell/">LinkedIn Profile</a>
  <br>
  <a href="http://www.kentling.com">HomePage</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
